use_frameworks!

platform :ios, '11.0'

install! 'cocoapods',  :preserve_pod_file_structure => true

target 'VietQRPay_Example' do
  pod 'VietQRPay',
  :path => '../'

  target 'VietQRPay_Tests' do
    inherit! :search_paths
  end
  
end
